{{- if not (include "is-openshift-4" .) }}
{{- if .Values.rbac.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-init
  labels:
{{ include "sidecar-injector-init.labels" . | indent 4 }}
rules:
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["create", "get", "watch", "delete"]
{{- if .Values.rbac.autoApproveCSR }}
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/approval"]
  verbs: ["update"]
{{- end }}
{{- end }}
{{- end }}
