{{- if not (include "is-openshift-4" .) }}
{{- if .Values.rbac.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-init
  labels:
{{ include "sidecar-injector-init.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ .Release.Namespace }}-init
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.initServiceAccountName }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
