apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
{{ include "sidecar-injector.labels" . | indent 4 }}
    cloudbees: sidecar-injector
{{- if include "is-openshift-4" . }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: cloudbees-sidecar-injector
{{- end }}
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
{{ include "sidecar-injector.instance-name" . | indent 4 }}
    app.kubernetes.io/component: cloudbees-sidecar-injector
